name: Build
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        optimize: [Debug, ReleaseSmall, ReleaseFast, ReleaseSafe]
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.11.0

      - name: Build
        run: zig build install "-Doptimize=${{matrix.optimize}}"
